data = struct('feedGasFlowRate', (117000.0+90000.0)*24.0/1.0e6, ...
    'feedGasTemperature', 28.5, ...
    'feedGasPressure', 42.4, ...
    'absorberFeedGasTemperature', 30.5, ...
    'absorberFeedGasPressure', 42.4, ...
    'leanTEGFlowRate', 5432.0*1.1, ...
    'leanTEGTemperature', 36.3, ...
    'flashDrumPressure', 5.0, ...
    'reboilerPressure', 1.23, ...
    'condenserTemperature', 94.0, ...
    'condenserPressure', 1.0, ...
    'reboilerTemperature', 200.3, ...
    'strippingGasRate', 100.0, ...
    'strippingGasFeedTemperature', 120.0, ...
    'regenerationGasCoolerTemperature', 35.0, ...
    'TEGpumpIsentropicEfficiency', 0.75, ...
    'finefilterdeltaP', 0.01, ...
    'carbonfilterdeltaP', 0.01, ...
    'numberOfEquilibriumStagesTEGabsorber', 5, ...
    'stageEfficiencyTEGabsorber', 0.55, ...
    'stageEfficiencyStripper', 0.5, ...
    'numberOfEquilibriumStagesStripper', 4, ...
    'UAvalueLeanRichTEGHeatExchanger', 16100.0);

% Ocp-Apim-Subscription-Key available from: https://api-test.portal.equinor.com/products/neqsim-live
options = weboptions('KeyName','Ocp-Apim-Subscription-Key','KeyValue','xxxxxx');
options.Timeout = 300.0
options.HeaderFields = matlab.net.http.HeaderField('Content-Type','application/json');
response = webwrite('https://api-test.gateway.equinor.com/neqsim/jsv/dehydSim', jsonencode(data),options)